--TUNING VALUES
---------------------------------------------------------------------------------------------

--local TUNING = GLOBAL.TUNING
local seg_time = 30
local total_day_time = seg_time*16

TUNING.TVACHIEVEMENTS =
{
	TAPESFOUND = 30,
	ABILITIESUSED = 9, --total # of tape abilities
	SUNKENCHESTS = 1,
}

TUNING.TAPEDROPRATES =
{
	DEBUG = 0.5,
	TREE = 0.05,
	BOULDER = 0.125,
	HOUSE = 0.47,
	PACKAGE = 0.1,
	HOLE = 0.1,
	GRAVE = 0.4,
	JACKPOT = 0.5, --chance rolled alongside 2 (so 2-3 technically)
	JACKPOTRARELOOTCOUNT = 1, --amount of tape caches found in jackpots
	FORAGE = 0.018,
	TUMBLE = 0.025,
	RUMMAGE = 0.07, --0.15,
	MISCRARE = 0.33,
	OTHER = 0.016,
}

TUNING.TVHEADGUY_HEALTH = 100
TUNING.TVHEADGUY_HUNGER = 100
TUNING.TVHEADGUY_SANITY = 150
TUNING.TVHEADGUY =
{
	HEALTH = 100,
	HUNGER = 100,
	SANITY = 150,
	WIMPDURATION = 2.5,
	HUNGERMULT = 0,
	HEALTHMULT = 0.66,
	SANITYMULT = 1,
	ITCHMETERMAX = 100,
	ITCHMETERDECAY = 28/total_day_time,
	--ITCHMETERKILLRATE = 0.66,
	ITCHMETER_THRESH = 0.1,
	DEFAULTITCHRESTORE = 30/total_day_time,
	PUNISHMENTINTERVAL = 10,
	PUNISHMENTAMT = -20,
	TAPEFINDRANGE = 40,
	AMULETDRAIN = -2.5,
}

TUNING.TVSKILLTREE = {
	EJECT_ITCH_COST = -5,

	ARCHIVE_FREEUSE_CHANCE = 0.25,

	BIGGERMETER_1 = 125,
	BIGGERMETER_2 = 150,
	BIGGERMETER_3 = 200,

    EFFICIENTCOMBAT_DEFAULT_MULT = 1,
    EFFICIENTCOMBAT_1_MULT = 0.90,
    EFFICIENTCOMBAT_2_MULT = 0.75,
    EFFICIENTCOMBAT_3_MULT = 0.60,

	INVIS_PLANAR_DMG_BONUS = 12,

	ELECTRIC_PLANAR_DMG_BONUS = 12,
	ELECTRIC_NEWRESISTANCE = 0.6,

	LIGHTNING_MAXZAPS = 3,
	LIGHTNING_PLANAR_DMG_BONUS = 12,

    RESEARCH_BLUEPRINT_SPAWN_CHANCE = 0.015, --rolled every second

    SCANNER_EXTRA_VIEW_DIST = 12,
    SCANNER_BONUSMAP_INTERVAL = 0.5,
	SCANNER_NEWRAREREVEALCHANCE = 0.4,

    SYSRESTORE_BONUSSANITY = 5,
	SYSRESTORE_MAXHP = 0.02,

	PIGTAPE_PIGELITE_CD = 60,
	PIGTAPE_NUM_OF_PIGELITES = 3,

	NIGHTVIS_DUSK_NEWINTERVAL = 18,
	NIGHTVIS_DUSK_NEWDURATION = 20,

	SHADOWFIND_1_PITY = 0.005,
	SHADOWFIND_1_PITYSMALL = 0.0005,
	SHADOWFIND_1_EXTRATAPECHANCE = 0.25,

	SHADOWFIND_2_PITY = 0.01,
	SHADOWFIND_2_PITYSMALL = 0.001,
	SHADOWFIND_2_EXTRATAPECHANCE = 0.5,

	LUNARFIND_1_PITY = 0.005,
	LUNARFIND_1_PITYSMALL = 0.0005,
	LUANRFIND_1_EXTRATAPECHANCE = 0.20,

	LUNARFIND_2_PITY = 0.01,
	LUNARFIND_2_PITYSMALL = 0.001,
	LUANRFIND_2_EXTRATAPECHANCE = 0.4, --lunar chances are lower because it's much less risky than being insane

	LEVEL1BONUS = 0.2,

	SHADOWDROPS_JUNK_CHANCE = 0.25,
	SHADOWDROPS_1_CHANCE = 0.4,
	SHADOWDROPS_2_CHANCE = 0.25,
	SHADOWDROPS_JUNK = {
		"ash",
	},
	SHADOWDROPS_1_LOOT = {
		"nightmarefuel",
	},
	SHADOWDROPS_2_LOOT = {
		"horrorfuel", "dreadstone",
	},

	LUNARDROPS_JUNK_CHANCE = 0.25,
	LUNARDROPS_1_CHANCE = 0.4,
	LUNARDROPS_2_CHANCE = 0.25,
	LUNARDROPS_JUNK = {
		"moon_tree_blossom",
	},
	LUNARDROPS_1_LOOT = {
		"moonglass", "moonglass", "moonrocknugget",
	},
	LUNARDROPS_2_LOOT = {
		"purebrilliance", "lunarplant_husk",
	},

	SHADOWTAPEEXPLODE_RADIUS = 20,
	SHADOWTAPEEXPLODE_PLANAR_DAMAGE = 10,
	SHADOWTAPEEXPLODE_VULNERABILITY = 1.2,
	SHADOWTAPEEXPLODE_DURATION = 30,


	LUNARTAPEEXPLODE_RADIUS = 12.5, --panflute is 15
	LUNARTAPEEXPLODE_SLEEPPOTENCY = 10, --panflute is 10
	LUNARTAPEEXPLODE_SLEEPTIME = 10, --panflute is 20

}

TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.TVHEADGUY = {
	"tape1"
}

--TUNING.TAPE_EXAMPLE =
--{
--	USES = 5,
--	ITCHVALUE = 12,
--	ITCHRESTORE = 60/total_day_time,
--	ITCHTICKRATE = 2,
--	DURATION = total_day_time/3,
--}

--itchvalue is the immediate value, itchrestore is the over time restoration (if applicable)
--don't forget tvheadguy loses 30 itch per day

TUNING.ITCH =
{
	VALUE = --initial
	{
		SUPERTINY = 1,
		TINY = 2,
		SMALL = 3,
		MEDSMALL = 5,
		MED = 8,
		MEDLARGE = 10,
		LARGE = 12,
		HUGE = 15,
	},
	RESTORE = --overtime
	{
		MINIMUM = 30/total_day_time,
		SMALL = 40/total_day_time,
		MED = 50/total_day_time,
		LARGE = 60/total_day_time,
		HUGE = 100/total_day_time,
		MOREHUGE = 320/total_day_time,
	}
}

TUNING.TAPE_PORTAL =
{
	USES = 20,
	ITCHVALUE = TUNING.ITCH.VALUE.TINY,
	ITCHRESTORE = TUNING.ITCH.RESTORE.LARGE,
	ITCHTICKRATE = 2,
	DURATION = seg_time*1,
}

TUNING.TAPE_BROADCAST =
{
	USES = 3,
	ITCHVALUE = TUNING.ITCH.VALUE.MEDSMALL,
	ITCHRESTORE = TUNING.ITCH.RESTORE.LARGE,
	ITCHTICKRATE = 2,
	DURATION = seg_time*2,
}

TUNING.TAPE_HYPERCAST =
{
	USES = 5,
	ITCHVALUE = TUNING.ITCH.VALUE.MEDSMALL,
	ITCHRESTORE = TUNING.ITCH.RESTORE.LARGE,
	ITCHTICKRATE = 2,
	DURATION = seg_time*2,
}

TUNING.TAPE_SCANNER =
{
	USES = 2,
	ITCHVALUE = TUNING.ITCH.VALUE.MED,
	ITCHMINIVALUE = TUNING.ITCH.VALUE.SUPERTINY/3, --value restored on every pulse
	ITCHRESTORE = TUNING.ITCH.RESTORE.SMALL,
	ITCHTICKRATE = 2,
	DURATION = total_day_time,
	INTERVAL = 25,
	RAREREVEALCHANCE = 0.30, --not the actual reveal chance, only spawns a cache if this chance passes *and* it can find a valid spot
	POIREVEALCHANCE = 0.1, -- chance to reveal map around an important structure
}

TUNING.TAPE_NIGHTVIS =
{
	USES = 10,
	ITCHVALUE = TUNING.ITCH.VALUE.MEDSMALL,
	ITCHRESTORE = TUNING.ITCH.RESTORE.MED,
	ITCHTICKRATE = 2,
	DURATION = total_day_time/3,
	DAYINTERVAL = 8,
	DUSKINTERVAL = 20,
	DUSKDURATION = 10,
}

TUNING.TAPE_SLOWMO =
{
	USES = 5,
	ITCHVALUE = TUNING.ITCH.VALUE.MEDLARGE,
	ITCHRESTORE = TUNING.ITCH.RESTORE.SMALL,
	ITCHTICKRATE = 2,
	DURATION = seg_time*4,
	RANGE = 20,
	--RUNSPEEDMOD = 2/3,
	SPEEDMOD_NONPLAYER = 2.2,
	SPEEDMOD_PLAYER = 1,
	INTERVAL = 1,
	EFFECTDURATION = 30,
}

TUNING.TAPE_ELECTRIC =
{
	USES = 5,
	ITCHVALUE = -TUNING.ITCH.VALUE.MED,
	ITCHRESTORE = 0,
	ITCHTICKRATE = 2,
	DURATION = seg_time*4,
	DAMAGE = 20, --dmg is multiplied by 1.5 cause electric
	RADIUS = 15,
	COOLDOWN = 2,
	RESISTANCE = 0.7,
}

TUNING.TAPE_SYSRESTORE =
{
	USES = 4,
	ITCHVALUE = TUNING.ITCH.VALUE.SMALL, --itchvalue is applied every pulse of the healing effect as well
	HEALTHVALUE = 2.5,
	SANITYVALUE = 0.33,
	ITCHRESTORE = 30/total_day_time, --enough regen to counteract passive drain, but no more
	ITCHTICKRATE = 2,
	DURATION = total_day_time/2,
	INTERVAL = 18,
}

TUNING.TAPE_PIG =
{
	USES = 5,
	ITCHVALUE = -TUNING.ITCH.VALUE.MEDLARGE,
	ITCHRESTORE = 0,
	ITCHTICKRATE = 2,
	DURATION = total_day_time/3,
	INTERVAL = 12,
	RANGE = 20,
	PIGBUFF_DURATION = 20,
	PIGBUFF_WORKEFFECTIVENESS_MODIFIER = 2.2,
	PIGBUFF_PLAYERABSORPTION_MODIFIER = 1/2,
	PIGBUFF_ATTACK_MULTIPLIER = 1.55,
	PIGBUFF_SPEED_MULTIPLIER = 1.3,
}

TUNING.TAPE_INVIS =
{
	USES = 5,
	ITCHVALUE = -TUNING.ITCH.VALUE.MED,
	ITCHRESTORE = -TUNING.ITCH.RESTORE.LARGE,
	ITCHTICKRATE = 2,
	DURATION = 10,
	AGGROTIME = 5,
	REAGGRORADIUS = 25,
}

TUNING.TAPE_LIGHTNING =
{
	USES = 5,
	ITCHVALUE = -TUNING.ITCH.VALUE.MEDLARGE,
	ITCHRESTORE = 0,
	ITCHTICKRATE = 2,
	DURATION = seg_time*4,
	FXINTERVAL = math.random(5, 10),
	INTERVAL = 5,
	INTERVAL_RAIN = 3,
	RANGE = 20,
	DAMAGE = 43,
	BOSS_DMG_BONUS = 57, --should total to 100
	MAXZAPS = 1,
	RUNSPEEDMOD = 2/3,
	EFFECTDURATION = 10,
}

TUNING.TAPE_INVIS_UPGRADED =
{
	USES = 5,
	ITCHVALUE = -TUNING.ITCH.VALUE.MEDLARGE,
	ITCHRESTORE = -TUNING.ITCH.RESTORE.LARGE,
	ITCHTICKRATE = 2,
	DURATION = 10,
	AGGROTIME = 5,
	REAGGRORADIUS = 25,
}

TUNING.TAPE_LIGHTNING_UPGRADED =
{
	USES = 5,
	ITCHVALUE = -TUNING.ITCH.VALUE.HUGE,
	ITCHRESTORE = -TUNING.ITCH.RESTORE.MED,
	ITCHTICKRATE = 2,
	DURATION = seg_time*4,
	FXINTERVAL = math.random(2, 5),
	INTERVAL = 5,
	INTERVAL_RAIN = 3,
	RANGE = 20,
	DAMAGE = 43,
	BOSS_DMG_BONUS = 57, --should total to 100
	PLANAR_DMG_BONUS = 12, --same as skilltree lightning tape bonus
	MAXZAPS = 5,
	RUNSPEEDMOD = 2/3,
	EFFECTDURATION = 10,
	BOOMBOOMS_MIN = 10, --changing min to below 10 will mess up the DoTaskInTimes in tapebuffs.lua
	BOOMBOOMS_MAX = 15,
	BOOMBOOM_SPAWNRADIUS = 5,
	BOOMBOOM_DMG = 13.5,
	BOOMBOOM_PLANARDMG = 5,
	BOOMBOOM_RADIUS = 2,
}

TUNING.CLONEDRONE = {
	MAXHEALTH = 100,
	DURATION = 30,
	DAMAGE = 27.2,
	PLANARDMG = 12,
	ATKPERIOD = 1,
	EXPLODE_RADIUS = 5,
	EXPLODE_DAMAGE = 50,
	EXPLODE_PLANARDMG = 15,
}